### ISSUE TITLE
Support for TTL?

### ISSUE THREAD

**Issue by lwl12** [nessgor/telegraf-session-dynamodb#1]
https://github.com/telegraf/telegraf/blob/128aa04b9e0cc9b624a780dff99aa9155ccd9943/session.js#L7

**Comment by nessgor** [comment]
Please try [feature/ttl](https://github.com/nessgor/telegraf-session-dynamodb/tree/feature/ttl)

**Comment by lwl12** [comment]
Sorry, I don't know how to use the beta branch... (New to NodeJS).
But I think the default value `-1` may cause the [DynamoDB TTL](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html) not work properly.

Great thanks for your work!

**Comment by nessgor** [comment]
> But I think the default value -1 may cause the DynamoDB TTL not work properly.

If the ttl value is set to -1, I have set up a conditional logic to omit the ttl field when updating the session. It will not update the ttl field to -1 in DynamoDB

**Comment by nessgor** [comment]
> Sorry, I don't know how to use the beta branch... (New to NodeJS).

Uninstall the previous one, then try
`npm install git://github.com/nessgor/telegraf-session-dynamodb.git#feature/ttl --save`

**Comment by nessgor** [comment]
@lwl12 Have you try the code? Does it work? I tried on my own dynamodb and the ttl is work.

**Comment by lwl12** [comment]
Fantastic! I just used it in an amateur project, so I haven't had time to test it yet, I am very sorry for that. And I think it should work well!
